version: '3'
services:
  app:
    container_name: bot-whatsapp
    image: golang:1.18.0-alpine3.15
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    ports:
      - 8080:8080
    restart: always
    environment:
      - TZ=Asia/Jakarta